---
- name: basic configuration
  template:
    src: freebsd/etc/rc.conf.j2
    dest: /etc/rc.conf
    owner: root
    group: wheel
    mode: 0644
  with_items:
  - { src: "freebsd/etc/rc.conf.j2", dest: "/etc/rc.conf" }
  - { src: "etc/resolv.conf.j2", dest: "/etc/resolv.conf" }

- name: create jails zpool
  command: "zpool create -O compression=lz4 zjails {{ zjails_dev }}"
  args:
    creates: /zjails
