---
- name: basic configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: wheel
    mode: 0644
  vars:
    hostname: "{{ inventory_hostname }}"
  with_items:
  - { src: "./freebsd/etc/rc.conf.j2", dest: "/etc/rc.conf" }
  - { src: "./common/etc/resolv.conf.j2", dest: "/etc/resolv.conf" }

- name: allow ssh key auth for root
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    state: present

- name: install generic packages
  pkgng:
    name: "{{ pkgs }}"
    state: present
  vars:
    pkgs:
    - vim-tiny
